### ISSUE TITLE
Issues of Magog Fireball Attack Fix.erm in TUM

### ISSUE THREAD

**Issue by Archer30** [Archer30/Third-Upgrade-Mod#13]
Two issues.

1. In TUM, Magog Fireball Attack Fix.erm doesn't check the existence of GEM. Thus when right-clicking on the shield, two dialogues asking for the friendly fire setting may appear.
2. The upgrade of Magog - Winged Magog doesn't work with Magog Fireball Attack Fix.erm at all. They can't damage allies by default and can't be changed (not big deal though)

Currently waiting for a decision on how to resolve these issues. @VMaiko1634 

My suggestion is to 

> **Delete Magog Fireball Attack Fix.erm from TUM**

Without this script, Winged Magog preserves the ability not to damage its own troops, and the conflict with GEM is resolved. As for Magog, they get to choose whether to inflict friendly damage when GEM is presented.

**Comment by VMaiko1634** [comment]
Ok, it will be deleted, put it on the list to be mentioned in the next changelog. About fireball and friendly damage it's for GEM, this will no longer concern the mod.
